# Problem 6.1

In [13]:
import numpy as np
from numpy.linalg import inv
import scipy.io
import pandas as pd

# For reproducibility
np.random.seed(1000)

In [33]:
# This function generates data based on the formula we input 
# For this time we will generate a square function added with a noise
f = lambda  x: x**2

In [249]:
# Closed function regression
def closed_function_regression(train_X, train_Y):
  X = np.array(train_X)
  y = np.array(train_Y)
  
  
  # TODO: Check again here  
  ones = np.ones(len(X))
  X = np.column_stack((ones, X))
  y = np.array(y)
        
  Xt = transpose(X)
  product = dot(Xt, X)
  theInverse = inv(product)
  w = dot(dot(theInverse, Xt), y)
        
  return w
        
        

In [312]:
df = scipy.io.loadmat("/Users/bagustrihatmaja/Downloads/HW1_Data/dataset1.mat")

X_trn = df['X_trn']
Y_trn = df['Y_trn']


closed_function_regression(X_trn, Y_trn)

array([[ 17.81209242],
       [  4.8607913 ]])

In [370]:
def shuffle_data(train_X, train_Y, batch_size):
    X = train_X
    y = train_Y
    
    random_indices = np.random.choice(len(X), len(y), replace=False)
    
    X_shuffled = X[random_indices,:]
    y_shuffled = y[random_indices]
    mini_batches = [(X_shuffled[i:i+batch_size,:], y_shuffled[i:i+batch_size]) for
                   i in range(0, len(y), batch_size)]
    return mini_batches
    

def mini_gradient_descent(train_X, train_Y, learning_rate, num_iter, batch_size):
    # Debug
    # print(train_X)
    
    # Prepare the data
    X = np.array(train_X)
    y = np.array(train_Y)
    
    # TODO: Check why do we need to put 1 here
    # ones = np.ones(len(X))
    # X = np.column_stack((ones, X))
    y = np.array(y)
    
    # Randomize the data and split into samples
    df = shuffle_data(X, y, batch_size)
    
    # DEBUG
    # print(type(X[0]))
    
    # Get the dimension
    x_dim = X.shape[1]

    
    # DEBUG
    #print("Dimension of splitted X: ", x_dim)
    
    # Set the initial tetha and other initial variables
    theta = np.zeros((x_dim, 1))
    
    # DEBUG
    # print(theta)
    
    # Debug
    # print("Zero vector: \n", theta)
    
    start_i = 0
    
    # Create the loop
    for i in range(start_i + 1, num_iter + 1):
        # For each randomized-mini-batch
        for j in range(0, len(df)):
            X = df[j][0]
            y = df[j][1]
            # Debug
            # print("-----\n", X)
            y_hat = np.dot(X, theta)
            theta = theta - learning_rate * np.dot(X.T, y_hat - y)
        
    return theta

In [ ]:
# Debug
# print(type(X_trn))
# print(X_trn[0])

def create_polinomial_array(element, n):
    pol = np.empty([1, n+1])
    # Debug
    # print(pol)
    for i in range(0, n+1):
        # Debug
        # print("Element: \n", element)
        pol[0][i] = element**i
        
    return pol[0]
        
degree = 3
# degree + 1 for 1's in the first column
X_trn_new = np.ndarray((len(X_trn), degree + 1))

i = 0
for x in X:
    X_trn_new[i] = create_polinomial_array(x, degree)
    i += 1
        

mini_gradient_descent(X_trn_new, Y_trn, 0.001, 12, 10)

[[  1.00000000e+00   1.41883768e+00   2.01310035e+00   2.85626262e+00]
 [  1.00000000e+00  -3.08617234e+00   9.52445974e+00  -2.93941243e+01]
 [  1.00000000e+00  -2.33266533e+00   5.44132754e+00  -1.26927961e+01]
 [  1.00000000e+00  -2.38076152e+00   5.66802543e+00  -1.34942169e+01]
 [  1.00000000e+00  -5.37074148e-01   2.88448641e-01  -1.54918308e-01]
 [  1.00000000e+00   3.03807615e+00   9.22990671e+00   2.80411595e+01]
 [  1.00000000e+00   2.66933868e+00   7.12536897e+00   1.90200230e+01]
 [  1.00000000e+00   9.21843687e-01   8.49795784e-01   7.83378879e-01]
 [  1.00000000e+00   2.49298597e+00   6.21497906e+00   1.54938556e+01]
 [  1.00000000e+00  -3.90380762e+00   1.52397139e+01  -5.94929112e+01]
 [  1.00000000e+00  -2.09218437e+00   4.37723543e+00  -9.15798355e+00]
 [  1.00000000e+00  -2.00400802e-01   4.01604813e-02  -8.04819264e-03]
 [  1.00000000e+00  -2.90981964e+00   8.46705033e+00  -2.46375893e+01]
 [  1.00000000e+00  -1.89979960e+00   3.60923852e+00  -6.85682989e+00]
 [  1.

array([[  6.44531338e+60],
       [ -3.84591723e+61],
       [  9.02556008e+61],
       [ -4.66368145e+62]])

# Problem 6.3